[package]
name = "just-formatter"
version = "1.0.0"
edition = "2024"
description = "Format justfile from stdin to stdout."
license = "MIT"
repository = "https://github.com/eli-yip/just-formatter"

[dependencies]
tempfile = "3.19.1"
